### ISSUE TITLE
Rejointse3.exe n'utilise pas la bonne IP après un chg_ip_se3.sh

### ISSUE THREAD

**Issue by ljoets** [SambaEdu/se3master#12]
Après avoir lancé le script chg_ip_se3.sh pour changer l'IP du serveur.
Au lancement sur un client à intégrer, du scipt rejointse3.exe, l'IP affichée est encore l'ancienne.
Il est nécessaire d'effectuer un dpkg-reconfigure se3-domain pour que le script récupère la bonne IP.

**Comment by mollef** [comment]
Il faut refaire les domscripts donc update-domscripts.sh doit suffir. A vérifer que update_logonpy.sh et var/cache/se3_install/wpkg-install.sh soient bien lancé par le script, sinon à prévoir aussi.

**Comment by denis-b** [comment]
Le 20/11/2017 à 21:37, mollef a écrit :
>
> Il faut refaire les domscripts donc update-domscripts.sh doit suffir. 
> A vérifer que update_logonpy.sh et 
> var/cache/se3_install/wpkg-install.sh soient bien lancé par le script, 
> sinon à prévoir aussi.
>
>
de mon côté j'ai pu tester la nouvelle methode sysprep avec des w7, et 
maintenant cela devrait fonctionner. Si c'est bon demain je commite la 
modif sur sambaedu-client-windows, et on peut le conseiller y compris 
pour les w7 !
