### ISSUE TITLE
Pas de fichier changelog

### ISSUE THREAD

**Issue by swirly** [SambaEdu/se3master#13]
Le paquet ne contient pas de fichier changelog ni au niveau de la racine ni dans debian/changelog

Il est difficile de savoir quelles ont été les modifications à chaque version, sauf à voir toutes les modifications de code.

Le plus propre, dans l'esprit debian, serait d'avoir un debian/changelog avec la syntaxe debian appropriée 

https://www.debian.org/doc/manuals/maint-guide/dreq.en.html#changelog

Je ne trouve pas la debian policy en html, voici le pdf (4.4, changelog)
https://www.debian.org/doc/debian-policy/policy.pdf

**Comment by mollef** [comment]
Nouvelle structure de paquet prévue pour se4
