### ISSUE TITLE
detection de l'os

### ISSUE THREAD

**Issue by denis-b** [SambaEdu/se3master#15]
On a pas mal de soucis à cause de la detection de l'os, on passe par des méthodes plus ou moins fiables et non pérennes :

- samba %a renvoie XP ou Vista, cela nous fait une belle jambe....

- smbclient renvoie un truc, à condition d'être authentifié et en smb1. En smb3 il n'y a rien.

- net rpc registry query .... renvoie tout ce que l'on veut à condition d'avoir activé l'accès au registre distant et d'être authentifié.

Juste une idée toute simple : ne pourrait-on pas lors de la mise au domaine enregistrer l'info dans le ldap ou ad, et s'en servir ensuite ? cela éviterait pas mal de soucis.

on récupère la chaine fournie par la commande ver :  Microsoft Windows [version 10.0.16299.64]

et on ajour l'attribut description à machine$

description: Microsoft Windows [version 10.0.16299.64]

Donc dans logon.sh on met :

```
eval $(ldapsearch -xLLL "(uid=$machine$)" description | grep description | sed 's/\(^description: Microsoft Windows.*\[version \([0-9]\+\)\.\([0-9]\+\)\.\([0-9]\+\)\.\([0-9]\+\)\].*$\)/os=\2; build=\4; arch=\5/g')
```

et à mon avis on passe directement $build aux scripts en dernier

**Comment by SambaEdu** [comment]
Mais en  voila une idée qu'elle est bonne :)
ldapsearch -xLLL uid=sp3unat$ description
description: xp 
Je viens d'ajouter l'attribut avec pla.....ça marche on dirait :) 

y-a-il un intérêt de récupérer l'info à un autre moment qu'à l'intégration ?
