### ISSUE TITLE
Pas d'échappement dans les requêtes SQL de gestion des clef

### ISSUE THREAD

**Issue by swirly** [SambaEdu/se3master#16]
Dans le fichier edit_cle.php, les requêtes ne sont pas préparées et la chaine n'est pas échappée.

Si on a un \ dans la valeur de clef, il disparait à l'intégration dans la base SQL.

Pour éviter les problèmes de ce genre, le mieux est de préparer les requêtes :
http://php.net/manual/fr/mysqli.prepare.php

**Comment by mollef** [comment]
Partie de code abandonnée sur se4
