### ISSUE TITLE
Gitlab mirror?

### ISSUE THREAD

**Issue by Neustradamus** [SambaEdu/se3master#17]
Gitlab -> Github:
- https://docs.gitlab.com/ee/workflow/repository_mirroring.html

**Comment by mollef** [comment]
migration vers Gitlab ok

**Comment by Neustradamus** [comment]
No the github is not updated from Gitlab:
- https://docs.gitlab.com/ee/workflow/repository_mirroring.html

**Comment by Neustradamus** [comment]
Any news?

The mirror (gitlab -> github) for all projects do not work.
