### ISSUE TITLE
suppression définitive depuis la gestion des parcs ne supprime pas du dhcp

### ISSUE THREAD

**Issue by SambaEdu** [SambaEdu/se3master#4]
**La suppression définitive depuis la gestion des parcs ne supprime pas la résa au niveau  du dhcp comme annoncé** 
dixit la liste :

> Quelle est la procédure qui convient pour supprimer _définitivement_
> toute trace d'une machine dans le Se3 ?
> 
> Est-ce bien la "suppression complète" depuis la page de gestion des
> parcs ? Est-ce qu'en procédant ainsi la réservation DHCP est également
> supprimée, et quid concernant l'annuaire et OCS ?
> 
> Alors que la suppression "complète" précise que la machine sera supprimée du dhcp, la réservation d'ip est n'en fait pas supprimée du tout ; on se demande bien  d'ailleurs ce qui est supprimé du dhcp ?
> Quant à OCS, je ne saurais être très catégorique.

**Comment by lolo4992** [comment]
Indépendant de se3master. Problème réglé que le module se3-dhcp depuis plusieurs mois
