### ISSUE TITLE
Extinction et reboot des clients linux

### ISSUE THREAD

**Issue by jcmousse** [SambaEdu/se3master#9]
Problème pour les ordres de reboot ou d'extinction des clients linux :
# system ( "/usr/bin/ssh -o StrictHostKeyChecking=no ConnectTimeout=1 root@".$ip." reboot");
L'option "ConnectTimeout" ne passe pas et fait planter la commande.

A tester avec :
# system ( "/usr/bin/ssh -o StrictHostKeyChecking=no root@".$ip." reboot");
(Cette modif semble régler le problème)

**Comment by SambaEdu** [comment]
ConnectTimeout=1 est bien la bonne option, simplement il manque visiblement -o dans la commande 
system ( "/usr/bin/ssh -o StrictHostKeyChecking=no -o ConnectTimeout=1 root@".$ip." reboot");
devrait régler le problème tout en conservant l'option qui a son intêret

**Comment by SambaEdu** [comment]
https://github.com/SambaEdu/se3master/commit/3f6b3764832dd61aac8d757ccf00e77ca36dbe65
